[phases.setup]
nixPkgs = [
  "cmake",
  "gcc",
  "gnumake",
  "python310Full",
  "python310Packages.pip",
  "zlib",
  "libjpeg",
  "libpng",
  "boost"
]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "gunicorn recursos.wsgi:application"
