[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip",   # <- Adiciona pip corretamente
  "gcc",
  "cmake",
  "zlib",
  "libjpeg",
  "libpng",
  "boost"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn recursos.wsgi:application"
