[phases.setup]
nixPkgs = [
  # Python completo, com pip/setuptools incluídos
  "python310Full",

  # Dependências de sistema para compilar dlib, etc.
  "cmake",
  "gcc",
  "gnumake",
  "zlib",
  "libjpeg",
  "libpng",
  "boost"
]

[phases.install]
cmds = [
  # já há pip no python310Full, então você pode chamar pip diretamente
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn recursos.wsgi:application"
