[phases.setup]
nixPkgs = [
  "python310Full",
  "curl",
  "gcc",
  "gnumake",
  "zlib",
  "libjpeg",
  "libpng",
  "boost"
]

[phases.install]
cmds = [
  # Faz o download do get-pip.py
  "curl -sS https://bootstrap.pypa.io/get-pip.py -o get-pip.py",

  # Instala o pip manualmente
  "python3 get-pip.py",

  # Atualiza pip e instala dependências
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "gunicorn recursos.wsgi:application"
