services:
  - type: web
    name: meu-sistema-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn recursos.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: meu-banco
          property: connectionString

databases:
  - name: meu-banco
    plan: free
